#!/usr/bin/python
from heartbeat_lib import HeartbeatMonitor, HEARTBEAT_PORT, HEARTBEAT_REPEAT, HEARTBEAT_TIMEOUT
import argparse
import signal
import time

parser = argparse.ArgumentParser(description="Monitors one or more hosts for heartbeat until SIGINT is received")
parser.add_argument('hosts', action="append", type=str)
parser.add_argument('-p', action="store", type=int, help="port", dest="port", default=HEARTBEAT_PORT)
parser.add_argument('-t', action="store", type=int, help= "timeout", dest="timeout", default=HEARTBEAT_TIMEOUT)
parser.add_argument('-r', action="store", type=int, help= "repeat", dest="repeat", default=HEARTBEAT_REPEAT)
args= parser.parse_args()

p,t,r= args.port, args.timeout, args.repeat
hosts= args.hosts

monitors= [HeartbeatMonitor(host, p,t,r) for host in hosts]
map(HeartbeatMonitor.start, monitors)


def ctrl_c_handler(signal, frame):
        map(HeartbeatMonitor.stop, monitors)
        exit(0)
        
signal.signal(signal.SIGINT, ctrl_c_handler)
signal.pause()  #wait for ctrl-c
