#!/bin/bash
#checks for a heartbeat (in this case a simple open socket)

HOST=$1
NUMBER_OF_TRIES=$2
PORT=23576
TIMEOUT=1
COMMAND="nc -w $TIMEOUT -z $HOST $PORT"


if [[ $NUMBER_OF_TRIES == "" ]]; then NUMBER_OF_TRIES=1; fi

SUCESS=12302
while [ $SUCESS -ne 0 ] && [[ $NUMBER_OF_TRIES>0 ]] 
	do
	$COMMAND
	SUCESS=$?
	NUMBER_OF_TRIES=$(( $NUMBER_OF_TRIES -1 ))
	done
exit $SUCESS
