#!/bin/bash
#daemonizes heartbeat_monitor, logs to file
#more ugly hacks...

HOST=cb.goncalopp.com
LOGFILE=/var/log/heartbeat.log

#trap "kill 0" SIGINT SIGTERM EXIT
trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT
heartbeat_monitor $HOST >> $LOGFILE 2>&1 &
while true
	do
	sleep 1
	done
