#!/usr/bin/python
import daemon
import time
import lockfile
import os, pwd, grp
import argparse
import sys

from heartbeat_lib import HeartbeatMonitor


def drop_privileges(uid_name='nobody', gid_name='nogroup'):
    if os.getuid() != 0:
        return
    running_uid = pwd.getpwnam(uid_name).pw_uid
    running_gid = grp.getgrnam(gid_name).gr_gid
    os.setgid(running_gid)
    os.setuid(running_uid)
    os.setgroups([])
    os.umask(077)


def run_function():
    with open(HEARTBEAT_LOGFILE) as f:
        log_function= lambda x: f.write(x+"\n")
        monitors= [HeartbeatMonitor(host) for host in HEARTBEAT_HOSTS]
        for monitor in monitors:
            monitor.change_log_function(log_function)
            monitor.start()
        while True:
            time.sleep(1);

def start():
    pass

def stop():
    pass

def restart():
    pass

def reload():
    pass

def wrong_argument(x):
    print "Wrong argument:",x
    sys.exit(1)

    
parser = argparse.ArgumentParser(description="starts, stops, or restarts heartbeat_monitor")
parser.add_argument('action', action="store", type=str)

args= parser.parse_args()
actions= {'start':start, }
if args.action=="start":
    pass

    
f= open(logfile, "a")
with daemon.DaemonContext(pidfile=lockfile.FileLock('/var/run/heartbeat_md.pid'),):
    main()

