#!/bin/bash
#heartbeat daemon (provides heartbeat)
#ugly hack since "nc -k" doesn't seem to work on all systems...

trap "kill 0" SIGINT SIGTERM EXIT
#trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT
nc -k -l 23576 &
while true 
	do
	sleep 1
	done
