#!/usr/bin/python
import daemon
import time
import os, pwd, grp

from heartbeat_lib import HeartbeatMonitor

def drop_privileges(uid_name='nobody', gid_name='nogroup'):
    if os.getuid() != 0:
        return
    running_uid = pwd.getpwnam(uid_name).pw_uid
    running_gid = grp.getgrnam(gid_name).gr_gid
    os.setgid(running_gid)
    os.setuid(running_uid)
    os.setgroups([])
    os.umask(077)


def main():
    with open(HEARTBEAT_LOGFILE) as f:
        log_function= lambda x: f.write(x+"\n")
        monitors= [HeartbeatMonitor(host) for host in HEARTBEAT_HOSTS]
        for monitor in monitors:
            monitor.change_log_function(log_function)
            monitor.start()
        while True:
            time.sleep(1);

f= open(logfile, "a")
with daemon.DaemonContext():
    main()

