#!/bin/bash
#daemonizes heartbeat_monitor, logs to file
#more ugly hacks...

#trap "kill 0" SIGINT SIGTERM EXIT
trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT
heartbeat_monitor cb.goncalopp.com >> /var/log/heartbeat.log 2>&1 &
while true
	do
	sleep 1
	done
